name: 1 - CriarOperator
on:
  workflow_dispatch:
   inputs:
      namespace:
        required: true
jobs:
  CreateOperator:
    runs-on: runner-deployment 
    steps:
      - uses: actions/checkout@v4
      - run: |
          helm install arc \
          --namespace ${{ inputs.namespace }} \
          --create-namespace \
          oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller

