name: 2- CriarNamespaceRunners
on:
  workflow_dispatch:
   inputs:
      namespace:
        required: true
jobs:
  CreateNamespace:
    runs-on: runner-deployment 
    steps:
      - uses: actions/checkout@v4
      - run: |
          kubectl create namespace ${{ inputs.namespace }}
