name: 3 - CriarSecret
on:
  workflow_dispatch:
   inputs:
      namespace:
        required: true
jobs:
  CreateSecret:
    runs-on: runner-deployment 
    steps:
      - uses: actions/checkout@v4
      - run: |
          kubectl create secret generic github_secret \
          --namespace=${{ inputs.namespace }} \
          --from-literal=github_app_id=${{ secrets.ARC_APP_ID }} \
          --from-literal=github_app_installation_id=${{ secrets.ARC_INSTALLATION_ID }} \
          --from-literal=github_app_private_key="${{ secrets.ARC_PRIVATE_KEY }}"
