name: HelmUpgrade
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        options:
        - default
      installation_name:
        required: true
jobs:
  Helm_upgrade:
    runs-on: runner-deployment 
    steps:
      - uses: actions/checkout@v4
      - run: |
          helm upgrade --install ${{ inputs.installation_name }} \
          --namespace "arc-runners" \
          -f inventories/values.yaml \
          oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set

