name: PrepareNamespaces
on:
  workflow_dispatch:
jobs:
  Helm_upgrade:
    runs-on: runner-deployment 
    steps:
      - uses: actions/checkout@v4
      - run: |
          helm upgrade "arc-runner-set" \
          --namespace "arc-runners" \
          -f inventories/values.yaml \
          oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set

