name: PrepareNamespaces
on:
  workflow_dispatch:
jobs:
  CreateSecret:
    runs-on: runner-deployment 
    steps:
      # - run: |
      #     kubectl create secret generic pre-defined-secret \
      #     --namespace=arc-runners \
      #     --from-literal=github_app_id=${{ secrets.ARC_APP_ID }} \
      #     --from-literal=github_app_installation_id=${{ secrets.ARC_INSTALLATION_ID }} \
      #     --from-literal=github_app_private_key=${{ secrets.ARC_PRIVATE_KEY }}
      - run: |
          INSTALLATION_NAME="arc-runner-set"
          NAMESPACE="arc-runners"
          helm install "${INSTALLATION_NAME}" \
          --namespace "${NAMESPACE}" \
          --create-namespace \
          -f values.yaml \
          oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set

